script_template: inno_setup.iss
app_id: D2328B63-29DD-4BD2-BEDD-E6E16F67F06B
app_name: FlClashX
publisher: pfizrak
publisher_url: https://github.com/pfizrak/FlClashX
display_name: FlClashX
executable_name: FlClashX.exe
output_base_file_name: FlClashX.exe
setup_icon_file: ..\windows\runner\resources\app_icon.ico
locales:
  - lang: ru
  - lang: en
privileges_required: admin
